program             = { item };

item                = definition
                    | statement;

definition          = enum_def
                    | struct_def
                    | variable_def
                    | function_def;

statement           = expression ";";

(* ====== ENUM ====== *)

enum_def            = "#" identifier "{" enum_variant { "," enum_variant } "}";

enum_variant        = identifier [ "(" type { "," type } ")" ];

(* ===== STRUCT ===== *)

struct_def          = "$" identifier "{" struct_field { "," struct_field } "}";

struct_field        = identifier ":" type;

(* ==== VARIABLE ==== *)

variable_def        = type identifier "=" expression ";";

(* ==== FUNCTION ==== *)

function_def        = "@" identifier "(" [ parameter_list ] ")" "->" type "{" function_body "}";

parameter_list      = parameter { "," parameter };

parameter           = type identifier;

function_body       = { statement } [ expression ];

(* === EXPRESSION === *)

expression          = comparison_expr;

comparison_expr     = additive_expr [ comparison_op additive_expr ];

comparison_op       = "==" | "!=" | "<" | ">" | "<=" | ">=";

additive_expr       = multiplicative_expr { ( "+" | "-" ) multiplicative_expr };

multiplicative_expr = unary_expr { ( "/" | "*" | "%" ) unary_expr };

unary_expr          = [ "-" | "!" ] postfix_expr;

postfix_expr        = primary_expr { suffix };

suffix              = "." identifier
                    | "::" identifier
                    | "(" [ expression { "," expression } ] ")";

primary_expr        = identifier
                    | literal
                    | struct_init
                    | "(" expression ")";

struct_init         = "{" [ expression { "," expression } ] "}";

(* ====== TYPE ====== *)

type                = primitive_type
                    | identifier;

primitive_type      = "Int" | "Float" | "Bool" | "String" | "Unit";

(* ==== LITERALS ==== *)

identifier          = letter { letter | digit | "_" };

literal             = int_lit | float_lit | bool_lit | string_lit;

float_lit           = digit { digit } "." digit { digit };

int_lit             = digit { digit };

bool_lit            = "true" | "false";

string_lit          = '"' { ? all visible characters ? } '"';

letter              = "A" | ... | "Z"
                    | "a" | ... | "z";

digit               = "0" | ... | "9";

newline             = "\n";

indent              = "\t";
